[package]
name = "rticonnector"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.169"
rticonnector-sys = { path = "../rticonnector-sys" }
# [build-dependencies]
# bindgen = "0.69.4"
