[package]
name = "rticonnector"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rticonnector-sys = { path = "../rticonnector-sys" }
serde = "1.0.217"
serde_json = "1.0.138"
thiserror = "2.0.11"

