name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Load SharedOjects
      run: cp -r rticonnector-sys/lib/linux-x64/* /bin/
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
